### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by dkrm0** [DrakeW/corgi#22]
Hi

Nice project that you have here, but what prevents me from using it is that it does not follow the XDG Base Directory and store his config files on `$HOME/.corgi` ([as seen here](https://github.com/DrakeW/corgi/blob/master/config/config.go#L21))

It would be good if you could follow this specification here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Mainly the `$XDG_CONFIG_HOME` variable.

Thanks in advance :)

**Comment by DrakeW** [comment]
hi @dkrmr , thanks for the suggestion! I don't see the env variable being set on my mac and did some googling, it seems to be something linux specific?
I'll make changes so that if `$XDG_CONFIG_HOME` is set, `.corgi` will be initialized there, otherwise it'll default to `$HOME/.corgi`. sounds good?

**Comment by dkrm0** [comment]
Sounds perfect :)

And yes, it is Linux specific.

**Comment by DrakeW** [comment]
Requested changes has landed in develop! if you would like to try it out first you could build `corgi` from scratch :) but expect an official release some time around early next week! Thanks

**Comment by dkrm0** [comment]
Thx for your changes! I tested it but there is a minor inconvenient. Directories in `XDG_CONFIG_HOME` are not hidden (no leading `.`). Can you change it ?

**Comment by dkrm0** [comment]
I created a pull request for you, #29, that resolves this issue. I also factorized the use of `XDG_CONFIG_HOME` as it can be used to have a more homogene cross-platform configuration scheme

**Comment by DrakeW** [comment]
thanks for contributing! PR reviewed, and we can have more code related discussion over there :)

**Comment by DrakeW** [comment]
https://github.com/DrakeW/corgi/releases/tag/v0.2.3 has shipped with the requested feature included
