### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by jkbbwr** [DrakeW/corgi#23]

**Comment by DrakeW** [comment]
Stay tuned, `corgi` is on its way to grab the `fish` 🐟

**Comment by DrakeW** [comment]
@jkbbwr fish support has landed in develop branch! if you would like to try it out before v0.2.3 is officially rolled out you can build the project from scratch following README instructions

**Comment by DrakeW** [comment]
https://github.com/DrakeW/corgi/releases/tag/v0.2.3 has shipped with the requested feature included
