### ISSUE TITLE
How about a way to export your snippets to a file that can be sourced in your ~/.aliases ?

### ISSUE THREAD

**Issue by edburns** [DrakeW/corgi#24]
For systems that don't have corgi, is it possible to export your snippets to something you could source from your .aliases file?

**Comment by DrakeW** [comment]
hi @edburns , thanks for bringing this up. do you mean something like export to a shell script? and if so do you think it's okay be asked to fill in the template fields before exporting?

**Comment by edburns** [comment]
>>>>> On Tue, 12 Jun 2018 22:34:05 -0700, Junyu Wang <notifications@github.com> said:

JW> hi @edburns , thanks for bringing this up. do you mean something
JW> like export to a shell script? and if so do you think it's okay be
JW> asked to fill in the template fields before exporting?

A shell script export is fine, as long as it can be sourced such that my
snippets are runnable by name.  A questionnairre seems like a fine
tradeoff.

Ed

-- 
| edward.burns@oracle.com | office: +1 407 458 0017

**Comment by DrakeW** [comment]
Code changes have landed in develop, and if you would like to try it out you can try building the project following the instructions. Next release it soon-to-come!

**Comment by DrakeW** [comment]
https://github.com/DrakeW/corgi/releases/tag/v0.2.3 has shipped with the requested feature included
