### ISSUE TITLE
Multi line commands

### ISSUE THREAD

**Issue by OneWebPro** [DrakeW/corgi#25]
Corgi is not supporting multi line commands during `corgi new` functionality. For example pasting command like:
```
docker run -p 2181:2181 -p 9092:9092 \
--env ADVERTISED_HOST="172.17.0.1" \
--env ADVERTISED_PORT=9092 \
--env NUM_PARTITIONS="2" \
--env TOPICS="topic1,topic2" \
spotify/kafka
```
will end with only first line `docker run -p 2181:2181 -p 9092:9092`

**Comment by DrakeW** [comment]
This seems to be a restriction posed by the input reading library that corgi uses, haven't found a solution yet but I will look into it

**Comment by DrakeW** [comment]
raised question in https://github.com/chzyer/readline/issues/147, still waiting for their response

**Comment by OneWebPro** [comment]
I found in readline an example https://github.com/chzyer/readline/blob/master/example/readline-multiline/readline-multiline.go - @DrakeW  can you maybe take a look?

**Comment by DrakeW** [comment]
@OneWebPro Thanks for looking into it! And I've merged changes to develop and will be in the next release, if you would like to try it out please follow the instruction to build the project from scratch.

**Comment by junyu-w** [comment]
v0.2.4 has been released with the requested feature!
