### ISSUE TITLE
HOME replacement variable in configuration paths

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [DrakeW/corgi#31]
When I define a snippet in `snippet.json`, I want to be able to have something along the lines of:

```
{
  "snippets": [
    {
      "file_loc": "~/.corgi/snippets/git_new_branch.json",
      "title": "git_new_branch"
    }
  ],
  "is_meta_dirty": false
}

```

Because I use Corgi on both my work and personal machines, where work dictates what my home directory has to be on that machine, but obviously not on the others. Currently Corgi fails in this case because it doesn't unwrap the tilde.

# Solution Suggestions
1. I'm fine with something like "$HOME" being implemented, where Corgi looks for that value and calls out to an environment variable, but maybe it would make more sense to just treat all values that start with a dollar sign as environment variables and error out from there?
2. I'm also fine with tilde being replaced if it's found at the beginning of a particular path.

I'm also okay with actually implementing this if others or the maintainer decide it's valuable. I may well issue a PR in that vein.

**Comment by DrakeW** [comment]
hi @verygoodsoftwarenotvirus , can you check what is your `snippets_dir` path in your `.corgi/corgi_conf.json`? since corgi uses that one as the prefix for snippet file location. And when corgi initializes itself, it will try to unwrap the value of `$HOME` or `$XDG_CONFIG_HOME` (as of 0.2.3, if `$XDG_CONFIG_HOME` is specified) and use them in the configuration file

**Comment by verygoodsoftwarenotvirus** [comment]
Hi @DrakeW I saw some references to `$XDG_CONFIG_HOME`, and had tried that, with disappointing results:

![screenshot 2018-06-29 11 09 08](https://user-images.githubusercontent.com/1289344/42102905-fc98e588-7b8c-11e8-9287-c9288c6b9782.png)

I'm not ruling out the possibility that I'm totally screwing something up here.

**Comment by DrakeW** [comment]
this is interesting, because when corgi initializes itself it will try to read the value of either `$HOME` or `$XDG_CONFIG_HOME`, instead of use `$HOME` literally... can you check if those `$HOME` or `XDG_CONFIG_HOME` exists on your system's `env`? and to fix the issue - just manually replace the `$HOME` in your `corgi_conf.json` with its value should fix the issue

**Comment by verygoodsoftwarenotvirus** [comment]
So I did some debugging and found that in [`Load()`](https://github.com/DrakeW/corgi/blob/58ae11f9314aaaf28338c90985b647ccb43d5b11/config/config.go#L98):

- [`GetDefaultConfigHome()`](https://github.com/DrakeW/corgi/blob/58ae11f9314aaaf28338c90985b647ccb43d5b11/config/config.go#L100) does indeed determine the correct home directory to look for configuration files in, and 
- [`GetDefaultConfigFile()`](https://github.com/DrakeW/corgi/blob/58ae11f9314aaaf28338c90985b647ccb43d5b11/config/config.go#L103) detects the appropriate configuration file

however, when that configuration file is loaded, things like `config.SnippetsFile` contain `$HOME`, which isn't then unwrapped by subsequent attempts (by, say, the `exec` command), which results in stat errors.

If I add the following code:

```go
if _, ok := os.LookupEnv("HOME"); ok {
	if strings.Contains(config.SnippetsFile, "$HOME") {
		strings.Replace(config.SnippetsFile, "$HOME", os.Getenv("HOME"), -1)
	}

	if strings.Contains(config.SnippetsDir, "$HOME") {
		strings.Replace(config.SnippetsDir, "$HOME", os.Getenv("HOME"), -1)
	}
}
```

between [these two lines](https://github.com/DrakeW/corgi/blob/58ae11f9314aaaf28338c90985b647ccb43d5b11/config/config.go#L138-L139), all my problems are resolved (for whatever that's worth). 

I'm willing to issue a PR that includes this fix, but I want to make sure you're okay with the solution (for instance, should I be using `XDG_CONFIG_HOME` in the above code instead?).

Thanks again for all your hard work and concern. I promise you this PR comes out of an admiration and excitement about the benefits I receive from Corgi rather than anything negative. :)

**Comment by dkrm0** [comment]
@verygoodsoftwarenotvirus Do you want to choose the storage location of snippets without the `corgi_conf.json` file or choose the storage location of all _corgi_ files, including `corgi_conf.json` ?

**Comment by DrakeW** [comment]
sorry guys I've been busy and not very responsive lately... 

@verygoodsoftwarenotvirus your request about being able to choose location of snippets so it could be synced up to different machines using services like Dropbox, Box etc is definitely reasonable! 
And I think it's a nice addition to the `corgi config` command, maybe something like `corgi config --snippets <dir of your choice>`

I will mark this as a feature request, and include it in the next minor release.

**Comment by vinayak-gadkari** [comment]
I have a corgi_conf.json.template which uses the same config (environment var $XDG_CONFIG_HOME) as above. I just run an extra step in my .bashrc to dynamically create the actual corgi_conf.json as below

envsubst < corgi_conf.json.template > corgi_conf.json

**Comment by junyu-w** [comment]
v0.2.4 has been released with the requested feature!
