### ISSUE TITLE
Handling default values with spaces

### ISSUE THREAD

**Issue by vinayak-gadkari** [DrakeW/corgi#33]
"command": "find . -type f -name \u003cname='*'\u003e -exec \u003ccmd1='grep -i'\u003e  \\;",

How can I pass "grep -i" as a default value for the parameter cmd1?
I tried using quotes and escaping , nothing works. Please advise.

**Comment by DrakeW** [comment]
hi @vinayak-gadkari , this is indeed a bug and the fix has been merged to develop, you could follow the steps to build corgi from scratch or wait for the next release :) thanks!

**Comment by vinayak-gadkari** [comment]
Fantastic support @DrakeW :-)

**Comment by junyu-w** [comment]
v0.2.4 has been released with the requested feature!
