### ISSUE TITLE
Default values \ doc

### ISSUE THREAD

**Issue by plmuninn** [DrakeW/corgi#38]
There is no explanation how to use default values in snippets (how to set them). Also, better documentation (with some more examples) would be nice.

**Comment by junyu-w** [comment]
I have it doc-ed in this section https://github.com/DrakeW/corgi#define-template-fields-in-snippet, but it might not be comprehensive enough, I can definitely add more examples! :)

**Comment by plmuninn** [comment]
I think we can close it - I found it, I think it could be more explicitly shown ;). But still, if someone want then will find it.
