### ISSUE TITLE
/bin/bash: ssh: command not found when exec in corgi

### ISSUE THREAD

**Issue by AnsonT** [DrakeW/corgi#40]
Running on OSX/Bash
Saved an ssh command line in corgi, failed when using the command via corgi exec with this error
/bin/bash: ssh: command not found

other bash commands appear to work: python3, ls, echo.

which ssh
/usr/bin/ssh
(command line ssh works)

**Comment by junyu-w** [comment]
corgi under the hood executes each step as `$SHELL -c "<your command>"`, can you check what is your `SHELL` set to and does `ssh` work with it?

**Comment by AnsonT** [comment]
declare -x SHELL="/bin/bash"
$SHELL -c "ssh" runs properly

**Comment by AnsonT** [comment]
Found the issue, a unicode character was somehow added to the start of the command.
